// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd1_Ppm7JNKuXlTLDco3ZpkyOXtKHum40',
    appId: '1:846219115187:web:c97d565de2adaca8ee8ec6',
    messagingSenderId: '846219115187',
    projectId: 'nextu-career-coach',
    authDomain: 'nextu-career-coach.firebaseapp.com',
    storageBucket: 'nextu-career-coach.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt6I85MLmuh-iRuKZv5RbgKz2_6CbJ8AQ',
    appId: '1:846219115187:android:edec300b76ff5e99ee8ec6',
    messagingSenderId: '846219115187',
    projectId: 'nextu-career-coach',
    storageBucket: 'nextu-career-coach.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFTe5iFT0zCeD1Yh3MCiXkmMZHruXJr-0',
    appId: '1:846219115187:ios:2f64248f068641c8ee8ec6',
    messagingSenderId: '846219115187',
    projectId: 'nextu-career-coach',
    storageBucket: 'nextu-career-coach.firebasestorage.app',
    iosBundleId: 'com.nextu.app',
  );

}